server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joedayz/config-repository
          searchPaths: customer-service,customer-account-service
          username: joedayz
          password: 123