server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iscodem/config-repository
          searchPaths: customer-service,customer-account-service
          #username: iscodem
          #password: 123